print("B. Ramkishan Rao -- Tatha")
print("K. Sarojini -- Baama")
print("P. Madhava Rao -- Tatha")
print("T. Radha  -- Ammamma")
print("P. Prasad -- Tatha")
print("Subhardra -- Ammaamma")
print("M. Gauri Shankar Rao -- Tatha")
print("M. Parvathi -- Ammamma")
print("M. Kalyan Kumar -- Maama")
print("M. Srilatha")
print("M. Karthik -- Maama")
print("M. Shoba -- Atha")
print("B. Shashank -- Naana")
print("P. Srimanasa -- Amma")
print("Sridhar -- Babai")
print("P. Chandrika -- Pinni")
print("B. Ram -- Babai")
print("P. Sravani -- Pinni")
print("Manish -- Babai")
print("P. Madhurima -- Pinni")
print("M. Priya Kameshwari Sravya _-- Vadina")
print("B. Akshar -- Myself")
print("P. Aashrita -- Chelli")
print("M. Aadhya -- Maradhalu")
print("M. Nagasai Surya -- Maridhi")
print("B. Shikhar -- Thamudu")
print ("B. Eesha -- Chelli")
print("M. Akhil -- Maridhi")
print("P. Adhiti -- Chelli")
print("B. Rudransh -- Thamudu")
