print('This program predicts the sum of 5 - 3 digit - numbers. You will say a number and straight after that I will predict the sum')
num1 = int(input('Enter your 1st number:')) 
prediction_total = int(num1 + 1998)
print('The total will be ' + str(prediction_total))
num2 = int(input('Enter your 2nd number:'))
ournum1 = int(999 - num2)
print('Now its our turn ' + str(ournum1))
num3 = int(input('Enter your 3rd number:'))
ournum2 = int(999 - num3)
print('Our 2nd number is ' + str(ournum2))
print('Now add these up add you will see it is ' + str(prediction_total))
if num1 < 100: exit(); print('Invalid Response!')
if num1 > 999: exit(); print('Invalid Response!')
if num2 < 100: exit(); print('Invalid Response!') 
if num2 > 999: exit(); print('Invalid Response!')
if num3 < 100: exit(); print('Invalid Response!')
if num3 > 999: exit(); print('Invalid Response!')
